package main

func amazonCats() (c map[string]map[string][]string) {
	c = map[string]map[string][]string{
		"building": {
			"repairs": {
				"Chimney Sheep",
			},
		},
		"stock": {
			"extensions": {
				"Cetornie",
				"Chinco",
				"ewinever",
				"Henan Xuchang Alice Hair CO.,LTD",
			},
			"misc": {},
		},
		"marketing": {
			"courses": {},
			"other": {
				"AMEITECH",
			},
		},
		"staff": {
			"education": {},
			"social": {},
		},
		"sundries": {
			"refreshments": {
				"HOT BARGAINS",
				"Kraft Foods UK Ltd",
			},
			"magazines": {},
			"misc": {
				"Aken",
				"Andrex",
				"Anself",
				"AXHKIO",
				"BARBICIDE",
				"Barbicide",
				"Baylis & Harding",
				"Cussons",
				"Duracell",
				"Energizer Batteries",
				"Hangqiao",
				"JINLE",
				"Kimberly-Clark",
				"Kimberly-Clark Professional",
				"Muc-Off Ltd (UK)",
				"Nitrile",
				"Nutra4Radiance",
				"Q Connect",
				"SCA",
				"Straame",
				"VIROSA",
				"YIZHAO",
			},
		},
		"drawings": {
			"adam": {
				"Aenllosi",
				"AKAI Professional",
				"Bangcool",
				"Bialetti",
				"BITTBOY",
				"Commercial Marketing",
				"EMI Catalogue",
				"Harman",
				"JasonCarlMorgan",
				"Jim Dunlop",
				"Koninklijke Philips N.V.",
				"Levivo",
				"Luigi's",
				"Meda Pharmaceuticals",
				"No Bull Music Gear",
				"Pro-Kleen",
				"Roadster",
				"Rodo",
				"Roland",
				"Rotosound",
				"Sable",
				"Scotch-Brite",
				"Signify",
				"Smart Weigh",
				"Source Chemicals",
				"Stagg",
				"Stxe9rimar",
				"tado",
				"tomtoc",
				"toyuugo",
				"TUKO",
				"VASAGLE",
				"Weber",
				"Weber-Stephen Products",
				"WeChip",
				"Westland Horticulture",
				"WOLF-Garten",
				"ZOLLNER",
				"VonShef",
			},
			"izzy": {
				"AiDe",
				"Bayer Public Limited Company",
				"BEDWAY",
				"CEVA",
				"Chilly's",
				"Church and Dwight",
				"Conair",
				"Evergreen Garden Care Ltd",
				"Feliway",
				"First Response",
				"GloBrite",
				"GUANGZHOU SHANGYE COSMETIC TOOLS CO.LTD",
				"Hangzhou Clongene Biotech Co., Ltd.",
				"HelloSiam",
				"InnoBase",
				"joolihome living",
				"Joytech Healthcare Co.,Ltd",
				"JVL",
				"LSA International",
				"Mangata",
				"Medipaq",
				"Mingtu",
				"Mpow",
				"Onlineforu",
				"Opret",
				"OVAVIEWxae",
				"Panasonic",
				"Philips",
				"Polaroid",
				"Procter & Gamble",
				"Silentnight",
				"Sweet Dreamers",
				"TRIXES",
				"Vidillo",
				"Vitabiotics",
				"Vitabiotics Ltd",
				"Waneway",
				"Yandu",
				"Yousave Accessories",
				"ZBSM",
				"Youngever",
			},
		},
		"equipment": {
			"equipment": {
				"Acer",
				"Ameego",
				"Anker",
				"AONESY",
				"Asus",
				"AV Link",
				"Barkan",
				"BETIONE",
				"Bodum",
				"Bulk Hardware",
				"CHUANGXINYOUPIN",
				"COMHOMA",
				"CZJ",
				"D'Addario Ltd",
				"Display4top",
				"DIVCHIxae",
				"Drxe4ger Safety AG & Co. KGaA",
				"Duronic",
				"FITFIRST",
				"FKA Brands Ltd",
				"fowong",
				"GAOHOU",
				"GLOBEGOU WZ CO.,LTD",
				"GUOHONG",
				"Hair Tools",
				"Harbour Housewares",
				"Head Jog",
				"IBRAxae",
				"IREENUO",
				"Jelly Comb",
				"Keple",
				"Lawrence Hardware",
				"Leisida",
				"LLRY-R",
				"Lusta LED Co., Ltd",
				"LYTIVAGEN",
				"Manfrotto",
				"Merrimen",
				"MODERN LIFE",
				"NAD",
				"Neewer",
				"Netgear",
				"Nicute",
				"Niluoya",
				"NLR",
				"OMERIL",
				"PANGHU",
				"rhinocables",
				"Rotolight",
				"SAMTIAN",
				"SIMBR",
				"Snowkids",
				"SPARES2GO",
				"Strait-Line",
				"Syncwire",
				"Tangle Teezer",
				"TCL",
				"Toshiba",
				"TRB",
				"UGREEN GROUP LIMITED",
				"Ugreen Group Limited",
				"uni",
				"Vileda",
				"Y.S. Park",
				"yorten",
				"Yosou",
			},
		},
		"other": {
			"other": {
				"AUPROTEC",
				"Beslagsboden",
				"DIVCHI",
				"DK Tools LTD",
				"KNIGHTSPED.Co",
				"Mila",
				"sb components",
				"Singularity Supplies Ltd",
				"Solus",
				"Sterling Locks",
				"Toyvian",
			},
		},
	}
	return
}
