package main

func amazonCats() (c map[string]map[string][]string) {
	c = map[string]map[string][]string{
		"building": {
			"repairs": {
				"Chimney Sheep",
				"Bonlux",
				"LLRY",
				"Sterling",
			},
			"salon refits": {
				"NAD",
				"Nad",
				"Wesco",
			},
		},
		"stock": {
			"extensions": {
				"Ayina",
				"Cetornie",
				"Classically Silver",
				"Chinco",
				"ewinever",
				"Henan Xuchang Alice Hair CO.,LTD",
				"Crystals & Gems Uk",
				"Simply Gorgeous",
			},
			"misc": {},
		},
		"insurance": {
			"insurance": {
				"Protect your bubble.com by Assurant",
			},
		},
		"marketing": {
			"courses": {},
			"other": {
				"AMEITECH",
			},
		},
		"staff": {
			"education": {},
			"social":    {},
		},
		"sundries": {
			"refreshments": {
				"2WORK",
				"HOT BARGAINS",
				"Kraft Foods UK Ltd",
				"Mondelez",
				"FENICAL",
				"H HARLEY STREET CARE",
				"HAKACC",
				"Fresh 365",
				"Mu Mianhua",
				"Xhuan",
			},
			"magazines": {},
			"gloves": {
				"SousVideTools",
			},
			"misc": {
				"Amazon Basics",
				"K-Mart Limited",
				"Youngever LLC",
				"Utopia Towels",
				"Thepaperbagstore",
				"Stanley",
				"SAGUARO",
				"Rovtop",
				"Aken",
				"Andrex",
				"- Deleted",
				"Anself",
				"AXHKIO",
				"BARBICIDE",
				"Barbicide",
				"Baylis & Harding",
				"Carex Health Brands",
				"Cussons",
				"Duracell",
				"Energizer Batteries",
				"Hangqiao",
				"indiadeals24x7",
				"JINLE",
				"Kimberly-Clark",
				"Kimberly-Clark Professional",
				"Kleenex",
				"Muc-Off Ltd (UK)",
				"Nitrile",
				"Nutra4Radiance",
				"Q Connect",
				"Reccisokz",
				"SCA",
				"Smithers Oasis",
				"Straame",
				"Tork",
				"VIROSA",
				"YIZHAO",
				"CZSM",
				"Newell Rubbermaid",
				"Dymo",
			},
		},
		"drawings": {
			"adam": {
				"Schneider Electric",
				"BG Electrical",
				"Vinyl Clear",
				"SUPJOYES",
				"Yogibare",
				"Trung Nguyen",
				"Taylor Tools",
				"Sage By Heston Blumenthal",
				"Sage",
				"Nicola Spring",
				"3M",
				"3M Virtua",
				"Aenllosi",
				"AKAI Professional",
				"ASNQ",
				"Bangcool",
				"Bialetti",
				"BITTBOY",
				"CB12",
				"Commercial Marketing",
				"D'Addario",
				"DXR",
				"EMI Catalogue",
				"EMI MKTG",
				"Harman",
				"IMS-UNIVERSAL",
				"indiadeals24x7",
				"Intralabs",
				"JasonCarlMorgan",
				"JBL",
				"Jim Dunlop",
				"Koninklijke Philips N.V.",
				"Levivo",
				"Luigi's",
				"LEVIVO",
				"Meda Pharmaceuticals",
				"NEBULA",
				"NETGEAR",
				"No Bull Music Gear",
				"No Bull",
				"Patio Magic!",
				"Patron",
				"Philips Hue",
				"Pro-Kleen",
				"Roadster",
				"Rodo",
				"Roland",
				"ROLAND",
				"Rotosound",
				"Sable",
				"Scotch-Brite",
				"Signify",
				"Singularity Supplies",
				"Smart Weigh",
				"Source Chemicals",
				"Spares2go",
				"Stagg",
				"Stxe9rimar",
				"tado",
				"tadoxb0",
				"The Retro Boutique",
				"tomtoc",
				"toyuugo",
				"TUKO",
				"VASAGLE",
				"Weber",
				"Weber-Stephen Products",
				"WeChip",
				"Westland Horticulture",
				"WOLF-Garten",
				"Wolf-Garten",
				"ZOLLNER",
				"VonShef",
				"Bang & Olufsen",
				"Budweiser",
				"Virgin EMI",
				"DAXINRUI",
				"Elinker",
				"EZStar",
				"Fender",
				"Hay House UK",
				"Yellow Kite",
				"Scope Healthcare",
				"JIANYIJIA Co.,Ltd",
				"Nilgiri Press",
				"Lavolta",
				"Ledger",
				"Lifesystems",
				"Oypla",
			},
			"izzy": {
				"JASBON",
				"Yousave Accessories",
				"WEKIN",
				"VATIN Officials",
				"ZACAL",
				"Stargazer",
				"Seven Seas Health Care Ltd",
				"Sass & Belle",
				"Sand & Sky",
				"ProCook",
				"INGFERTILITY",
				"PHIFO",
				"AiDe",
				"Bayer Public Limited Company",
				"BEDWAY",
				"BaByliss",
				"Canesflor",
				"CEVA",
				"Chilly's",
				"Church and Dwight",
				"Clearblue",
				"Conair",
				"Evergreen Garden Care Ltd",
				"Feliway",
				"First Response",
				"femometer",
				"FIRST RESPONSE",
				"Generic",
				"GloBrite",
				"GUANGZHOU SHANGYE COSMETIC TOOLS CO.LTD",
				"Hangzhou Clongene Biotech Co., Ltd.",
				"HelloSiam",
				"InnoBase",
				"IBUYKE",
				"joolihome living",
				"Joytech Healthcare Co.,Ltd",
				"JVL",
				"Kilner",
				"LSA International",
				"Lameila",
				"Mangata",
				"Medipaq",
				"Mingtu",
				"Mpow",
				"One Step",
				"Onlineforu",
				"Onlineforu lTD",
				"ovaview",
				"Opret",
				"OVAVIEWxae",
				"Panasonic",
				"Pre~Seed",
				"Philips",
				"Polaroid",
				"Procter & Gamble",
				"Pregnacare",
				"PUPOUSE",
				"Seven Seas",
				"Silentnight",
				"Sweet Dreamers",
				"TRIXES",
				"Vidillo",
				"Vitabiotics",
				"Vitabiotics Ltd",
				"Waneway",
				"Westland",
				"WISCHGXUN",
				"Yandu",
				"Yousave Accessories",
				"ZBSM",
				"Youngever",
				"151",
				"Fun And Glitter Ltd",
				"Gardman",
				"GCS LONDON",
				"HIGLL",
				"HIGLL",
				"INDRESSME",
				"LIVIVO",
			},
		},
		"equipment": {
			"equipment": {
				"Cleefun",
				"HAKUSHA",
				"humpun",
				"Wyze",
				"NEW'C",
				"EbestINC",
				"SanDisk",
				"Zeadio",
				"YKS",
				"Vogel's",
				"TP-Link",
				"SIXNWELL",
				"shulian",
				"Safescan/Market Match BV",
				"Russel Hobbs",
				"Quntis",
				"Pro Signal",
				"Acer",
				"ARTCISE",
				"ASUS",
				"Ameego",
				"Anker",
				"AONESY",
				"Amtech",
				"Asus",
				"Ausein",
				"AV Link",
				"Barkan",
				"BETIONE",
				"Bodum",
				"BODUM",
				"Bulk Hardware",
				"CHUANGXINYOUPIN",
				"COMHOMA",
				"Cooler Pioneer",
				"CZJ",
				"CXYP",
				"D'Addario Ltd",
				"Display4top",
				"DIVCHI",
				"DIVCHIxae",
				"Drxe4ger Safety AG & Co. KGaA",
				"Duronic",
				"Drxe4ger",
				"Energizer",
				"FITFIRST",
				"FKA Brands Ltd",
				"fowong",
				"GAOHOU",
				"GLOBEGOU WZ CO.,LTD",
				"GUOHONG",
				"Hair Tools",
				"Harbour Housewares",
				"Head Jog",
				"IBRAxae",
				"IBRA",
				"IREENUO",
				"JAOMON",
				"Jelly Comb",
				"Joby",
				"Keple",
				"KEPLIN",
				"Lawrence Hardware",
				"Leisida",
				"LLRY-R",
				"Lusta LED Co., Ltd",
				"LYTIVAGEN",
				"Manfrotto",
				"Merrimen",
				"Merriway",
				"MODERN LIFE",
				"Neewer",
				"Netgear",
				"NETGEAR",
				"Nicute",
				"Niluoya",
				"NLR",
				"NLR FUN",
				"OMERIL",
				"PANGHU",
				"rhinocables",
				"Rotolight",
				"SAMTIAN",
				"Salter",
				"SIMBR",
				"Snowkids",
				"SPARES2GO",
				"Strait-Line",
				"Syncwire",
				"Tangle Teezer",
				"TCL",
				"Toshiba",
				"TopMate",
				"TRB",
				"UGREEN GROUP LIMITED",
				"UGREEN",
				"Ugreen Group Limited",
				"uni",
				"Vileda",
				"YS PACK",
				"Y.S. Park",
				"yorten",
				"Yosou",
				"zeadio",
				"Apple Computer",
				"Beyond Your Thoughts",
				"Bisley",
				"Brabantia",
				"Breville",
				"BRTLX",
				"Carryme",
				"Porter & Woodman",
				"Chalkola",
				"SuperChalks",
				"Xinhenchen",
				"The Dustpan and Brush Store",
				"Concept4u",
				"Denman International Ltd",
				"DJI",
				"E-muse",
				"Epson",
				"Ex-Pro",
				"FlexiSpot",
				"E4U Electricals UK Ltd.",
				"Inateck",
				"JandCase",
				"kenable",
				"LeChamp",
				"Marko",
				"Microsoft",
				"Morphy Richards",
				"NEVERLAND Beauty & Health",
			},
		},
		"other": {
			"other": {
				"QLOUNI",
				"Aioneus",
				"Sabichi",
				"AUPROTEC",
				"Beslagsboden",
				"DIVCHI",
				"DK Tools LTD",
				"KNIGHTSPED.Co",
				"Mila",
				"Muc Off",
				"Protect your bubble.com",
				"Rabbitgoo",
				"sb components",
				"Singularity Supplies Ltd",
				"Solus",
				"Sterling Locks",
				"Toyvian",
				"Y.S.Park",
				"YS Park",
				"Amtico",
				"DiCUNO",
				"Home Treats",
				"Nexus (Jiaxing)",
				"VonHaus",
			},
		},
	}
	return
}
