package main

func GetCategories() (c map[string]map[string][]string) {
	c = map[string]map[string][]string{
		"wages": {
			"stylist": {
				"MR J SHARP",
				"JAMES SHARPE",
				"MISS L HALL",
				"GEORGIA LUTTON",
				"LAUREN THOMPSON",
				"LAYLA RELF",
				"ABBI GREEN",
				"MISS V ROWLAND",
				"KELLY REEDY",
				"JOANNE MAHONEY",
				"BRADLEY RYAN",
				"ABIGAIL CLARKE",
				"DAVID RANDLES",
				"LUCY WATSON",
				"LAUREN WATSON",
				"RUBY JOHNSON",
				"SOPHIE YOUDS",
				"BETH BROWN",
				"HARRISON DOOLEY",
				"SARAH CARTWRIGHT",
				"KATE O HALLORAN",
				"DOROTA SOKOLOWSKI",
				"VICTORIA NYLAND",
				"LOUISE BAILEY",
				"LILLY SMITH",
				"JAMIE BANNING-HIGH",
				"EVE SIMPSON",
				"REBECCA COTTON",
				"SARAH CUDDY",
				"SHAE HOUGHTON",
				"MISS I LAMB",
			},
			"freelance": {
				"NATALIE SHARPE",
				"MATHEW LANE",
				"MATTHEW LANE",
				"AMY WOODS",
				"MICHELLE RAILTON",
				"LEON PRITCHARD",
			},
			"other": {
				"ROSEMARIE WINTERBU",
			},
			"paye": {
				"HMRC CUSTOMS AND E",
				"FREDRICKSON",
				"ADVANTIS",
			},
			"pension": {
				"NEST",
			},
		},
		"taxes": {
			"vat": {
				"HMRC VAT",
				"HMRC E VAT",
			},
			"tax": {
				"HMRC NDDS",
				"HMRC - ACCOUNTS OF",
				"HMRC 600000000562153302",
				"HMRC 300000000784948091",
				"HMRC 200000000588802019",
				"1ST LOCATE UK",
			},
		},
		"utilities": {
			"energy": {
				"BRIT GAS",
				"SCOTTISH POWER",
				"EDF ENERGY",
				"BG BUSINESS",
				"WWW.BRITISHGAS.CO.",
				"SCOTTISHPOWER",
				"E.ON",
			},
			"water": {
				"WATER PLUS",
				"PASTDUE",
			},
			"telecoms": {"BRITISH TELECOM",
				"EE LIMITED",
				"BT GROUP",
				"O2 DEVICE PLAN",
				"O2 05056477/001",
				"EE & T-MOBILE",},
			"waste": {
				"ASH WASTE",
				"CATHEDRAL LEASING",
				"CATHEDRAL HYGIENE",
			},
			"other": {
				"CHUBB",
				"WWW.MY.CHUBB.CO.UK",
			},
		},
		"building": {
			"rent": {
				"MEREHALL ESTATES",
				"BETTERBOOZE LTD",
				"JENSON INVESTMENTS",
				"JENSEN INVESTMENTS",
			},
			"rates": {
				"WARRINGTON BOROUGH",
				"WARRINGTON CD",
				"WARRINGTON B.C.",
				"W.B.C MV INTERNET",
				"WBC NNDR",
			},
			"repairs": {
				"MR ROBERT A ANTONO",
				"A6 ROLLER SHUTTERS",
			},
			"base": {
				"NJS MAINTENANCE",
				"M SUTTON",
				"MODERN LIGHTING",
				"M A SUTTON",
				"JACOB INTERIORS",
			},
		},
		"stock": {
			"schwarzkopf": {
				"HENKEL",
			},
			"kevin murphy": {
				"ICON CONSULTANCY",
				"SWEET SQUARED",
			},
			"ghd": {
				"WWW.GHDHAIR.COM",
				"JAMELLA",
				"JEMELLA LTD",
				"JEMELLA",
				"GHD",
			},
			"olaplex": {
				"WWW.ASTONANDFINCHE",
			},
			"extensions": {
				"BEAUTY WORKS",
				"BEAUTYWORKS",
				"BALMAINHAIR.CO.UK",
				"THE WIGGINS",
				"SIMPLYHAIR",
				"BEAUTY WORX",
				"SP * HAIRMADEEASIS",
			},
			"gowns": {
				"WWW.FEEFORHAIR.CO.",
				"FEEL FOR HAIR",
			},
			"misc": {
				"WWW.SALONSDIRECT.C",
				"SALONEASY",
				"ALAN HOWARD",
				"ALAN HOWARD(STOCKP CD 6954",
				"SALLY SALON",
				"SALONS DIRECT",
				"WWW.SALON-SERVICES",
				"FA UK LIMITED",
				"CLOUD9",
				"AMERICAN CREW",
				"GOCARDLESS",
			},
		},
		"marketing": {
			"website": {
				"RACKSPACE",
				"HEROKU",
				"DIGITALOCEAN.COM",
				"FORGE.LARAVEL.COM",
				"DNSIMPLE",
				"123 REG",
			},
			"sms": {
				"TEXTANYWHERE",
				"TEXT ANYWHERE",
				"TEXTMAGIC.COM",
			},
			"software": {
				"ADOBE",
				"Evernote",
				"WWW.PHOREST.COM",
				"NDEVOR",
				"JETBRAINS",
				"JetBrains",
			},
			"courses": {
				"LARACASTS",
				"VUEMASTERY.COM",
			},
			"social media": {
				"BUFFER",
				"COSCHEDULE.COM",
				"COSCHEDULE",
				"LOOMLY US",
				"HTTPS://HEROPOST.I CA",
			},
			"advertising": {
				"GOOGLE",
				"FACEBK",
				"THREE BEST RATED",
			},
			"printing": {

			},
			"signage": {
				"WWW.DISCOUNTDISPLA",
				"WINDOWFILMS",
				"THE PRINTING PEOPL",
				"SG MANUFACTURING",
				"DISCOUNT DISPLAYS",
			},
			"other": {
				"POST OFFICE SELF",
				"PENTANGLE CARDS",
				"GRAFENIA",
				"INDEED",
			},
		},
		"insurance": {
			"insurance": {
				"CLOSE-COVERSURE",
				"BAUER CONSUMER MED",
				"VLS RE KLARNA",
				"VLS RE CLOSE BROS",
				"GROVE-DEAN.CO.UK",
				"CURRYS  3267567149",
			},
		},
		"staff": {
			"transport": {
				"TRAINLINE",
				"Trainline.com",
				"VIRGIN TRAINS",
			},
			"HR": {
				"D WRIGHT",
			},
			"education": {
				"PARAGON",
				"SALON PUNK",
				"FIRE EVENTS",
				"BEHINDTHECHAIR.COM",
			},
			"accommodation": {
				"Village Hotel Warr",
				"THE CUMBERLAND",
				"SUITES HOTEL KNOWS",
				"GREAT CUMBERLAND",
				"AIRBNB",
			},
			"social": {
				"PAPA JONES PIZZA",
				"MR LAU'S",
				"LAS RAMBLAS",
				"Just Eat",
				"FRIAR PENKETH",
				"DMN/DIRTYMARTINIMA",
				"Circo",
				"THE BOTANIST",
			},
		},
		"sundries": {
			"music": {
				"Spotify",
				"SPOTIFY",
				"PPLPRS",
				"PPL PRS",
			},
			"refreshments": {
				"VIMTO OUT",
				"DJ DRINK SOLUTIONS",
			},
			"magazines": {
				"DLT MEDIA",
			},
			"misc": {
				"WWW.GOMPELS.CO.UK",
				"VIKING",
				"TILLROLLSDIRECT.CO",
				"CARTRIDGEPEOPLE.CO",
				"WWW.COSTCO.CO.UK",
				"POUNDLAND",
				"POUND SUPER STORE",
				"MM NEWSAGENTS",
				"MARTIN MCCOLL",
				"COSTCO",
				"B&M",
			},
		},
		"paypal": {
			"paypal": {
				"PAYPAL",
			},
		},
		"amazon": {
			"amazon": {
				"AMZNMKTPLACE ",
				"AMZNMktplace",
				"Amazon",
				"AMZN",
				"AMZ*BC",
				"AMAZON",
			},
		},
		"loans": {
			"loans": {
				"KENNET",
				"INVESTEC",
				"QUANTUM",
				"JOHN LAMB",
				"D A CARTER",
				"LOAN",
			},
		},
		"bank": {
			"bank": {
				"NON-GBP TRANS FEE",
				"O/DRAFT INTEREST",
				"SERVICE CHARGES",
				"RETAIL MERCHANT SE",
				"RMS",
				"GLOBAL PAYMENTS",
				"EMS",
				"UNAUTH'D BORR. FEE",
				"RETURNED D/D",
				"OVERDRAFT FEE",
				"NON-STG TRANS FEE",
			},
		},
		"drawings": {
			"drawings": {
				"ADAM CARTER",
				"NETFLIX.COM",
				"APPLE.COM/BILL",
				"ITUNES.COM/BILL",
				"Audible.co.uk",
				"STARBUCKS",
				"LNK WARRINGTON",
				"Prime",
				"VISION DIRECT",
				"Kindle",
				"Amazon Prime*MB8HF",
				"WWW.ASOS.COM",
				"WWW.TWOSEASONS.CO.",
				"Audible UK",
				"WWW.MISSGUIDED.CO.",
				"VOLCOM SAS",
				"TOPPIK.CO.UK",
				"TICKETMASTER",
				"PropellerheadsCOM",
				"MCDONALDS",
				"GRUMPY MULE",
				"FGT*TICKETMASTER",
				"Etsy.com",
				"EASYJET",
				"DANIEL HANCOCK",
				"CHATURBIL",
				"APPLE.COM/UK",
				"ACOUSTIC CAFE",
				"SODASTREAM",
				"MADE.COM",
			},
		},
		"equipment": {
			"equipment": {
				"CURRYS CD",
				"TENZY",
				"JM-AC",
				"LADDERS UK",
				"SP * YOISCISSORS",
				"WWW ESPARES",
				"WWW.BUYSPARES.CO.U CD",
				"HOWHIGHBRANDS.CO.U",
				"AMBICOOL",
				"BARBER BLADES",
				"WWW.LEDSUPPLYANDFI",
			},
		},
		"accountant": {
			"accountant": {
				"CMT ACCOUNTING",
				"POS-HARDWARE LTD",
			},
		},
	}
	return
}
