package migrations

func paypalCats() (c map[string]map[string][]string) {
	c = map[string]map[string][]string{
		"building": {
			"repairs": {
				"The Wood Veneer Hub",
			},
		},
		"stock": {
			"olaplex": {
				"Aston & Fincher",
			},
			"kevin murphy": {
				"ICON CONSULTANCY",
				"SWEET SQUARED",
			},
			"ghd":        {},
			"extensions": {},
			"gowns":      {},
			"misc": {
				"saloneasy.com",
				"Salons Direct Ltd",
				"coolblades",
				"Alan Howard (Stockport) Ltd",
				"Hairdressing Supplies Lincoln Ltd",
				"Gompels HealthCare Ltd",
			},
		},
		"marketing": {
			"website": {
				"123-reg Limited",
				"123-reg Limited",
			},
			"sms": {},
			"software": {
				"Canva Pty Limited",
				"Dropbox International Unlimited Company",
			},
			"courses": {
				"Udemy Ireland, Ltd",
				"Packt Publishing Limited",
				"Manning Publications Co.",
				"Gumroad Inc",
				"Domestika Inc",
			},
			"social media": {},
			"advertising": {
				"Facebook",
				"Google",
			},
			"printing": {},
			"signage": {
				"XL Displays Ltd",
				"Discount Displays Ltd",
				"CUSTOM NEON PTY LTD",
				"Visual Signs & Graphics Ltd",
			},
			"other": {},
		},
		"staff": {
			"transport": {
				"Virgin Trains",
			},
			"HR":        {},
			"education": {},
			"accommodation": {
				"Travelodge Hotels Limited",
				"Booking.com BV",
			},
			"social": {},
		},
		"sundries": {
			"music": {
				"Spotify Finance Limited",
				"Spotify AB",
			},
			"refreshments": {},
			"magazines":    {},
			"misc": {
				"Amazon Basics",
				"The Cartridge People Ltd",
				"Costco UK",
				"Ideal Envelopes Limited",
				"Cartridge Save Limited",
			},
		},
		"drawings": {
			"adam": {
				"Fairdeal Music Limited",
				"adidas (UK) Limited",
				"ROUTE ONE RETAIL LIMITED",
				"www.twoseasons.co.uk",
				"Customer Service - Epoch",
				"epoch.com",
				"Grumpy Mule",
				"Tickets",
				"Ticketmaster UK Limited",
				"Gear4music Limited",
				"Reason Studios AB",
				"DisneyPlus",
				"Andertons Music Co",
				"The Guitar Amp and Keyboard Centre Ltd",
				"VOLCOM",
				"NAPALI SAS",
				"Ableton AG",
				"Aarke AB",
				"Vision Direct",
				"Air di Paolo Brini",
				"Hush Communications Canada Inc.",
				"premiumbeat.com",
				"INTERNATIONAL FIDELITY LTD",
			},
			"izzy": {
				"Sixty Stores Ltd",
				"ASOS.COM Ltd",
				"Airwair International Limited",
			},
		},
		"equipment": {
			"equipment": {
				"Toolstation Limited",
				"Park Cameras Ltd",
				"Analogue Wonderland",
				"Amara Living Limited",
				"Richer Sounds Plc",
				"Argos Limited",
				"Qualtex UK Ltd",
				"Connect Distribution Services Ltd",
				"IKEA Limited",
				"Sevenoaks Sound & Vision Ltd",
				"eSpares Ltd",
				"MPB Europe Limited",
				"Creative Video Productions Ltd.",
				"wirral Discount Supplies limited",
				"Cult Furniture ltd",
				"Next Retail Ltd",
				"Lights4fun Ltd",
			},
		},
		"other": {
			"other": {
				"Yoi Scissor Sharp UK",
				"Metals4u Ltd",
				"Hartington Heath LTD",
				"Lighting Styles Ltd",
				"John Lewis PLC",
				"Argofield Limited",
				"Internet Fusion Ltd",
				"Envato Pty Ltd",
				"Paul Ainley",
				"Virgin Money Giving Limited",
				"Reflective Supplies",
				"eBay (UK) Limited",
				"eBay UK Limited",
				"Kira Schneiders",
				"christopher reid",
				"Ultimate Wraps Ltd",
				"Joey Underwood",
				"david j stout",
				"永耀 李",
				"Apple Store",
				"Peggy Nash",
				"Real Cadence Ltd",
				"NAPALI SAS (Etablissement Soorts Hossegor)",
				"Paddle.com Market Limited",
				"Ecotrade Europe Ltd",
				"Warehouse Express Ltd",
				"LUZERN ECOMMERCE LTD",
				"eBay",
			},
		},
	}
	return
}
